steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "Dockerfile.worker"
      - "-t"
      - "us-central1-docker.pkg.dev/gen-lang-client-0807585847/v0-social/backend-worker:latest"
      - "."
images:
  - "us-central1-docker.pkg.dev/gen-lang-client-0807585847/v0-social/backend-worker:latest"
